/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnSplatRouteImport } from './routes/en.$'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/en/$',
  path: '/en/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/en/$': typeof EnSplatRoute
  '/en/': typeof EnIndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/en/$': typeof EnSplatRoute
  '/en': typeof EnIndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/en/$': typeof EnSplatRoute
  '/en/': typeof EnIndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/en/$'
    | '/en/'
    | '/api/file-uploads/$fileUploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/en/$'
    | '/en'
    | '/api/file-uploads/$fileUploadId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/en/$'
    | '/en/'
    | '/api/file-uploads_/$fileUploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WatchRoute: typeof WatchRoute
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  EnSplatRoute: typeof EnSplatRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/$': {
      id: '/en/$'
      path: '/en/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WatchRoute: WatchRoute,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  EnSplatRoute: EnSplatRoute,
  EnIndexRoute: EnIndexRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
